MyMVCProject/Models/ReadingLog.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadingLog
    {
        public int Id { get; set; }
        public string ReaderName { get; set; }
        public Nullable<System.DateTime> ClockIn { get; set; }
        public Nullable<System.DateTime> ClockOut { get; set; }
        public string BookName { get; set; }
        public string Author { get; set; }
        public Nullable<int> ReaderId { get; set; }
    
        public virtual Reader Reader { get; set; }
    }
}

MyMVCProject/Controllers/ReadingLogsController.cs
using MyMVCProject.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Gnostice.StarDocsSDK;

namespace MyMVCProject.Controllers
{
    public class ReadingLogsController : Controller
    {
        // GET: ReadingLogs
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ReadingLog readingLog)
        {
            string bookName = readingLog.BookName;
            string authorName = readingLog.Author;
            readingLog.ClockIn = DateTime.Now;
            readingLog.ClockOut = DateTime.Now;
            readingLog.ReaderId = Convert.ToInt32(Session["ReaderId"]);
            readingLog.ReaderName = Convert.ToString(Session["ReaderName"]);
            int Id = Convert.ToInt32(Session["ReaderId"]);
            using (MyDataBaseEntities dc = new MyDataBaseEntities())
            {
                dc.ReadingLog.Add(readingLog);
                dc.SaveChanges();
                var readingLogList = dc.ReadingLog.Where(a => a.ReaderId == Id).ToList();
                //var BookList = (readingLogList.Select(a => a.BookName)).ToList();
                //dc.ReadingLog.Where(a => a.ReaderId == readingLog.ReaderId).Select(a =>a.BookName).ToList();
                //return Redirect(ReaderDetails);
                //Console.Write(BookList);
                return View("BookList", readingLogList);
            }

        }

        [HttpGet]
        public ActionResult BookList()
        {
            using (MyDataBaseEntities dc = new MyDataBaseEntities())
            {
                int Id = Convert.ToInt32(Session["ReaderId"]);
                var readingLogList = dc.ReadingLog.Where(a => a.ReaderId == Id).ToList();
                //var BookList = (readingLogList.Select(a => a.BookName)).ToList();
                //dc.ReadingLog.Where(a => a.ReaderId == readingLog.ReaderId).Select(a =>a.BookName).ToList();
                //return Redirect(ReaderDetails);
                //Console.Write(BookList);
                return View("BookList", readingLogList);
            }
        }

        

        public ActionResult ReadBook()
        {
            string file = @"C:\Work\TopicReview.pdf";
            FileObject read_file = new FileObject(file);
            ViewerSettings viewerSettings = new ViewerSettings();
            viewerSettings.VisibleFileOperationControls.Open = true;

            ViewResponse viewResponse = MvcApplication.starDocs.Viewer.CreateView(
                read_file, null, viewerSettings);

            //Redirect
            return new RedirectResult(viewResponse.Url);
        }
    }
}

MyMVCProject/Views/ReadingLogs/BookList.cshtml
@model IEnumerable<MyMVCProject.Models.ReadingLog>

@{
    ViewBag.Title = "BookList";
}


<h2>BookList</h2>

@*<p>
    @Html.ActionLink("BookList", "BookList", "ReadingLogs")
</p>*@
<table class="table">
    <tr>
        @*<th>
            @Html.DisplayNameFor(model => model.ReaderName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClockIn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClockOut)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.BookName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Reader.ReaderName)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        @*<td>
            @Html.DisplayFor(modelItem => item.ReaderName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClockIn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClockOut)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.BookName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Author)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Reader.ReaderName)
        </td>*@
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

MyMVCProject/Views/ReadingLogs/Create.cshtml
@model MyMVCProject.Models.ReadingLog

@{
    ViewBag.Title = "Create";
}
<div class="form-horizontal">
    <h4>Search New Books</h4>
    <p>
        <input type="search" placeholder="Title or Author" id="bookname" />
        <input type="button" value="Search" id="BookSearch" />
    </p>
</div>
    <div id="results">

    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Add New Books</h4>
            <hr />
            @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.ReaderName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ReaderName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ReaderName, "", new { @class = "text-danger" })
                    </div>
                </div>*@

            @*<div class="form-group">
                    @Html.LabelFor(model => model.ClockIn, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ClockIn, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ClockIn, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ClockOut, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ClockOut, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ClockOut, "", new { @class = "text-danger" })
                    </div>
                </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.BookName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.BookName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BookName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
                    @Html.LabelFor(model => model.ReaderId, "ReaderId", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("ReaderId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ReaderId, "", new { @class = "text-danger" })
                    </div>
                </div>*@

            @*<h4>Continue Reading</h4>
                <div class="form-group">

                </div>*@

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Submit" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        <p>
            <h4>@Html.ActionLink("BookList", "BookList", "ReadingLogs")</h4>

        </p>
        @Html.ActionLink("Back to List", "Index")
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    @*scripts for ajax*@
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script></script>
    <script type="text/javascript">

        document.getElementById('BookSearch').addEventListener('click', bookSearch, false)

        function bookSearch() {
            var search = document.getElementById('bookname').value
            document.getElementById('results').innerHTML = ""
            console.log(search)
            $.ajax({
                url: "https://www.googleapis.com/books/v1/volumes?q=" + search,
                datatype: "json",
                success: function (data) {
                    for (i = 0; i < data.items.length; i++) {
                        results.innerHTML += "<h4>" + data.items[i].volumeInfo.title + "</h4>"
                        //results.innerHTML += "<h4>" + "Author" + "</h4>"
                        //for (j = 0; ((typeof (data.items[i].volumeInfo.authors != "undefined")) && (j < data.items[i].volumeInfo.authors.length)); j++)
                        //    {

                        //    results.innerHTML += "<h5>" + data.items[i].volumeInfo.authors[j] + "</h5>"

                        //}
                        if (typeof (data.items[i].volumeInfo.imageLinks) != "undefined") {
                            results.innerHTML += "<img src=" + data.items[i].volumeInfo.imageLinks.thumbnail + ">"
                        }
                        results.innerHTML += "<br" + "  " + "</br>"
                    }
                    console.log(data)
                },
                type: 'GET'
            });

        }
    </script>

MyMVCProject/Views/ReadingLogs/Delete.cshtml
@model MyMVCProject.Models.ReadingLog

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ReadingLog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Reader.ReaderName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reader.ReaderName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReaderName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReaderName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClockIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClockIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClockOut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClockOut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BookName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MyMVCProject/Views/ReadingLogs/Details.cshtml
@model MyMVCProject.Models.ReadingLog

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ReadingLog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Reader.ReaderName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reader.ReaderName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReaderName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReaderName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClockIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClockIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClockOut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClockOut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BookName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MyMVCProject/Views/ReadingLogs/Edit.cshtml
@model MyMVCProject.Models.ReadingLog

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ReadingLog</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ReaderName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReaderName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReaderName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClockIn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClockIn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClockIn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClockOut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClockOut, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClockOut, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReaderId, "ReaderId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ReaderId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ReaderId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

MyMVCProject/Views/ReadingLogs/Index.cshtml
@model IEnumerable<MyMVCProject.Models.ReadingLog>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Reader.ReaderName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReaderName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClockIn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClockOut)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BookName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Reader.ReaderName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReaderName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClockIn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClockOut)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BookName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Author)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>